//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Restaurante.Inputs
{
    
    
    /// <summary>
    /// Interface para a tabela VT_VENDA
    /// </summary>
    public partial interface IVenda : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Restaurante.Entidades.IMesacomandas ComandaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle ComandaHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valordigitado (VALORDIGITADO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 9999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> Valordigitado
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valortotal (VALORTOTAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> Valortotal
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela VT_VENDA
    /// </summary>
    public partial interface IVendaDao : IBusinessEntityDao<IVenda>
    {
    }
    
    /// <summary>
    /// DAO para a tabela VT_VENDA
    /// </summary>
    public partial class VendaDao : BusinessEntityDao<Venda, IVenda>, IVendaDao
    {
        
        public static VendaDao CreateInstance()
        {
            return CreateInstance<VendaDao>();
        }
    }
    
    /// <summary>
    /// Venda
    /// </summary>
    [EntityDefinitionName("VT_VENDA")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Venda : BusinessEntity<Venda>, IVenda
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Comanda = "COMANDA";
			public const string Valordigitado = "VALORDIGITADO";
			public const string Valortotal = "VALORTOTAL";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Restaurante.Entidades.IMesacomandas ComandaInstance
        {
            get
            {
                if (Comanda.Handle == null)
                {
					return null;
                }
                return Comanda.Instance;
            }
            set
            {
                if (value == null)
                {
					Comanda = null;
					return;
                }
                Comanda.Instance = (Benner.Restaurante.Entidades.Mesacomandas) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle ComandaHandle
        {
            get
            {
                return Comanda.Handle;
            }
            set
            {
                Comanda.Handle = value;
            }
        }
        
        /// <summary>
        /// Comanda (COMANDA.)
        /// Opcional = N, Invisível = False, Pesquisar = MESACOMANDAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Restaurante.Entidades.Mesacomandas> Comanda
        {
            get
            {
                return (Fields["COMANDA"] as EntityAssociation).Wrap<Benner.Restaurante.Entidades.Mesacomandas>(Benner.Restaurante.Entidades.Mesacomandas.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Comanda.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Comanda.Instance = value.Instance;
                    }
                    else
                    {
                        this.Comanda.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Valordigitado (VALORDIGITADO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 9999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> Valordigitado
        {
            get
            {
                return Fields["VALORDIGITADO"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORDIGITADO"] = value;
            }
        }
        
        /// <summary>
        /// Valortotal (VALORTOTAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> Valortotal
        {
            get
            {
                return Fields["VALORTOTAL"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORTOTAL"] = value;
            }
        }
    }
}
