//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Restaurante.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela CARTOES
    /// </summary>
    public partial interface ICartoes : IEntityBase
    {
        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<bool> Ativo
        {
            get;
            set;
        }
        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Cpf
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome do cliente (NOMECLIENTE.)
        /// Opcional = N, Invisível = False, Tamanho = 15
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string NomeCliente
        {
            get;
            set;
        }
        
        /// <summary>
        /// Numerocartao (NUMEROCARTAO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<long> Numerocartao
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela CARTOES
    /// </summary>
    public partial interface ICartoesDao : IBusinessEntityDao<ICartoes>
    {
    }
    
    /// <summary>
    /// DAO para a tabela CARTOES
    /// </summary>
    public partial class CartoesDao : BusinessEntityDao<Cartoes, ICartoes>, ICartoesDao
    {
        
        public static CartoesDao CreateInstance()
        {
            return CreateInstance<CartoesDao>();
        }
    }
    
    /// <summary>
    /// Cartoes
    /// </summary>
    [EntityDefinitionName("CARTOES")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Cartoes : BusinessEntity<Cartoes>, ICartoes
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ativo = "ATIVO";
			public const string Cpf = "CPF";
			public const string NomeCliente = "NOMECLIENTE";
			public const string Numerocartao = "NUMEROCARTAO";
		}

        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<bool> Ativo
        {
            get
            {
                return Fields["ATIVO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ATIVO"] = value;
            }
        }
        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Cpf
        {
            get
            {
                return Fields["CPF"] as System.String;
            }
            set
            {
                Fields["CPF"] = value;
            }
        }
        
        /// <summary>
        /// Nome do cliente (NOMECLIENTE.)
        /// Opcional = N, Invisível = False, Tamanho = 15
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string NomeCliente
        {
            get
            {
                return Fields["NOMECLIENTE"] as System.String;
            }
            set
            {
                Fields["NOMECLIENTE"] = value;
            }
        }
        
        /// <summary>
        /// Numerocartao (NUMEROCARTAO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<long> Numerocartao
        {
            get
            {
                return Fields["NUMEROCARTAO"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["NUMEROCARTAO"] = value;
            }
        }
    }
}
