//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Restaurante.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela COMANDAS
    /// </summary>
    public partial interface IComandas : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Tecnologia.Common.IEntityBase MesaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle MesaHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<long> Numero
        {
            get;
            set;
        }
        
        /// <summary>
        /// Ocupada (OCUPADA.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<bool> Ocupada
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela COMANDAS
    /// </summary>
    public partial interface IComandasDao : IBusinessEntityDao<IComandas>
    {
    }
    
    /// <summary>
    /// DAO para a tabela COMANDAS
    /// </summary>
    public partial class ComandasDao : BusinessEntityDao<Comandas, IComandas>, IComandasDao
    {
        
        public static ComandasDao CreateInstance()
        {
            return CreateInstance<ComandasDao>();
        }
    }
    
    /// <summary>
    /// Comandas
    /// </summary>
    [EntityDefinitionName("COMANDAS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Comandas : BusinessEntity<Comandas>, IComandas
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Mesa = "MESA";
			public const string Numero = "NUMERO";
			public const string Ocupada = "OCUPADA";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.IEntityBase MesaInstance
        {
            get
            {
                if (Mesa.Handle == null)
                {
					return null;
                }
                return Mesa.Instance;
            }
            set
            {
                if (value == null)
                {
					Mesa = null;
					return;
                }
                Mesa.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle MesaHandle
        {
            get
            {
                return Mesa.Handle;
            }
            set
            {
                Mesa.Handle = value;
            }
        }
        
        /// <summary>
        /// Mesa (MESA.)
        /// Opcional = S, Invisível = False, Pesquisar = MESAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation Mesa
        {
            get
            {
                return Fields["MESA"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.Mesa.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.Mesa.Instance = value.Instance;
                    }
                    else
                    {
                        this.Mesa.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<long> Numero
        {
            get
            {
                return Fields["NUMERO"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["NUMERO"] = value;
            }
        }
        
        /// <summary>
        /// Ocupada (OCUPADA.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<bool> Ocupada
        {
            get
            {
                return Fields["OCUPADA"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["OCUPADA"] = value;
            }
        }
    }
}
