//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Restaurante.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela ITEMPEDIDO
    /// </summary>
    public partial interface IItemPedido : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Restaurante.Entidades.IMesacomandas ComandaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle ComandaHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Entregue (ENTREGUE.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<bool> Entregue
        {
            get;
            set;
        }
        
        /// <summary>
        /// Hora Pedido (HORAPEDIDO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<System.DateTime> HoraPedido
        {
            get;
            set;
        }
        
        /// <summary>
        /// Observação (OBSERVACAO.)
        /// Opcional = S, Invisível = False, Tamanho = 15
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Observacao
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Restaurante.Entidades.IProduto ProdutoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle ProdutoHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela ITEMPEDIDO
    /// </summary>
    public partial interface IItemPedidoDao : IBusinessEntityDao<IItemPedido>
    {
    }
    
    /// <summary>
    /// DAO para a tabela ITEMPEDIDO
    /// </summary>
    public partial class ItemPedidoDao : BusinessEntityDao<ItemPedido, IItemPedido>, IItemPedidoDao
    {
        
        public static ItemPedidoDao CreateInstance()
        {
            return CreateInstance<ItemPedidoDao>();
        }
    }
    
    /// <summary>
    /// ItemPedido
    /// </summary>
    [EntityDefinitionName("ITEMPEDIDO")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class ItemPedido : BusinessEntity<ItemPedido>, IItemPedido
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Comanda = "COMANDA";
			public const string Entregue = "ENTREGUE";
			public const string HoraPedido = "HORAPEDIDO";
			public const string Observacao = "OBSERVACAO";
			public const string Produto = "PRODUTO";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Restaurante.Entidades.IMesacomandas ComandaInstance
        {
            get
            {
                if (Comanda.Handle == null)
                {
					return null;
                }
                return Comanda.Instance;
            }
            set
            {
                if (value == null)
                {
					Comanda = null;
					return;
                }
                Comanda.Instance = (Benner.Restaurante.Entidades.Mesacomandas) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle ComandaHandle
        {
            get
            {
                return Comanda.Handle;
            }
            set
            {
                Comanda.Handle = value;
            }
        }
        
        /// <summary>
        /// Comanda (COMANDA.)
        /// Opcional = S, Invisível = False, Pesquisar = MESACOMANDAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Restaurante.Entidades.Mesacomandas> Comanda
        {
            get
            {
                return (Fields["COMANDA"] as EntityAssociation).Wrap<Benner.Restaurante.Entidades.Mesacomandas>(Benner.Restaurante.Entidades.Mesacomandas.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Comanda.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Comanda.Instance = value.Instance;
                    }
                    else
                    {
                        this.Comanda.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Entregue (ENTREGUE.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<bool> Entregue
        {
            get
            {
                return Fields["ENTREGUE"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ENTREGUE"] = value;
            }
        }
        
        /// <summary>
        /// Hora Pedido (HORAPEDIDO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<System.DateTime> HoraPedido
        {
            get
            {
                return Fields["HORAPEDIDO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["HORAPEDIDO"] = value;
            }
        }
        
        /// <summary>
        /// Observação (OBSERVACAO.)
        /// Opcional = S, Invisível = False, Tamanho = 15
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Observacao
        {
            get
            {
                return Fields["OBSERVACAO"] as System.String;
            }
            set
            {
                Fields["OBSERVACAO"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Restaurante.Entidades.IProduto ProdutoInstance
        {
            get
            {
                if (Produto.Handle == null)
                {
					return null;
                }
                return Produto.Instance;
            }
            set
            {
                if (value == null)
                {
					Produto = null;
					return;
                }
                Produto.Instance = (Benner.Restaurante.Entidades.Produto) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle ProdutoHandle
        {
            get
            {
                return Produto.Handle;
            }
            set
            {
                Produto.Handle = value;
            }
        }
        
        /// <summary>
        /// Produto (PRODUTO.)
        /// Opcional = N, Invisível = False, Pesquisar = PRODUTO
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Restaurante.Entidades.Produto> Produto
        {
            get
            {
                return (Fields["PRODUTO"] as EntityAssociation).Wrap<Benner.Restaurante.Entidades.Produto>(Benner.Restaurante.Entidades.Produto.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Produto.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Produto.Instance = value.Instance;
                    }
                    else
                    {
                        this.Produto.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
