//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Restaurante.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela MESAS
    /// </summary>
    public partial interface IMesas : IEntityBase
    {
        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<long> Numero
        {
            get;
            set;
        }
        
        /// <summary>
        /// Ocupada (OCUPADA.)
        /// Opcional = N, Invisível = True, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<bool> Ocupada
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela MESAS
    /// </summary>
    public partial interface IMesasDao : IBusinessEntityDao<IMesas>
    {
    }
    
    /// <summary>
    /// DAO para a tabela MESAS
    /// </summary>
    public partial class MesasDao : BusinessEntityDao<Mesas, IMesas>, IMesasDao
    {
        
        public static MesasDao CreateInstance()
        {
            return CreateInstance<MesasDao>();
        }
    }
    
    /// <summary>
    /// Mesas
    /// </summary>
    [EntityDefinitionName("MESAS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Mesas : BusinessEntity<Mesas>, IMesas
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Numero = "NUMERO";
			public const string Ocupada = "OCUPADA";
		}

        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<long> Numero
        {
            get
            {
                return Fields["NUMERO"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["NUMERO"] = value;
            }
        }
        
        /// <summary>
        /// Ocupada (OCUPADA.)
        /// Opcional = N, Invisível = True, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<bool> Ocupada
        {
            get
            {
                return Fields["OCUPADA"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["OCUPADA"] = value;
            }
        }
    }
}
