//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Restaurante.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela MESACOMANDAS
    /// </summary>
    public partial interface IMesacomandas : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Restaurante.Entidades.IComandas ComandaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle ComandaHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Tecnologia.Common.IEntityBase MesaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle MesaHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valor Digitado (VALORDIGITADO.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> ValorDigitado
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valortotal (VALORTOTAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> Valortotal
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela MESACOMANDAS
    /// </summary>
    public partial interface IMesacomandasDao : IBusinessEntityDao<IMesacomandas>
    {
    }
    
    /// <summary>
    /// DAO para a tabela MESACOMANDAS
    /// </summary>
    public partial class MesacomandasDao : BusinessEntityDao<Mesacomandas, IMesacomandas>, IMesacomandasDao
    {
        
        public static MesacomandasDao CreateInstance()
        {
            return CreateInstance<MesacomandasDao>();
        }
    }
    
    /// <summary>
    /// Mesacomandas
    /// </summary>
    [EntityDefinitionName("MESACOMANDAS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Mesacomandas : BusinessEntity<Mesacomandas>, IMesacomandas
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Comanda = "COMANDA";
			public const string Mesa = "MESA";
			public const string ValorDigitado = "VALORDIGITADO";
			public const string Valortotal = "VALORTOTAL";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Restaurante.Entidades.IComandas ComandaInstance
        {
            get
            {
                if (Comanda.Handle == null)
                {
					return null;
                }
                return Comanda.Instance;
            }
            set
            {
                if (value == null)
                {
					Comanda = null;
					return;
                }
                Comanda.Instance = (Benner.Restaurante.Entidades.Comandas) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle ComandaHandle
        {
            get
            {
                return Comanda.Handle;
            }
            set
            {
                Comanda.Handle = value;
            }
        }
        
        /// <summary>
        /// Comanda (COMANDA.)
        /// Opcional = S, Invisível = False, Pesquisar = COMANDAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Restaurante.Entidades.Comandas> Comanda
        {
            get
            {
                return (Fields["COMANDA"] as EntityAssociation).Wrap<Benner.Restaurante.Entidades.Comandas>(Benner.Restaurante.Entidades.Comandas.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Comanda.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Comanda.Instance = value.Instance;
                    }
                    else
                    {
                        this.Comanda.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.IEntityBase MesaInstance
        {
            get
            {
                if (Mesa.Handle == null)
                {
					return null;
                }
                return Mesa.Instance;
            }
            set
            {
                if (value == null)
                {
					Mesa = null;
					return;
                }
                Mesa.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle MesaHandle
        {
            get
            {
                return Mesa.Handle;
            }
            set
            {
                Mesa.Handle = value;
            }
        }
        
        /// <summary>
        /// Mesa (MESA.)
        /// Opcional = N, Invisível = False, Pesquisar = MESAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation Mesa
        {
            get
            {
                return Fields["MESA"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.Mesa.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.Mesa.Instance = value.Instance;
                    }
                    else
                    {
                        this.Mesa.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Valor Digitado (VALORDIGITADO.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> ValorDigitado
        {
            get
            {
                return Fields["VALORDIGITADO"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORDIGITADO"] = value;
            }
        }
        
        /// <summary>
        /// Valortotal (VALORTOTAL.)
        /// Opcional = S, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> Valortotal
        {
            get
            {
                return Fields["VALORTOTAL"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORTOTAL"] = value;
            }
        }
    }
}
