//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Restaurante.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela PRODUTO
    /// </summary>
    public partial interface IProduto : IEntityBase
    {
        
        /// <summary>
        /// Categoria (CATEGORIA.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        ProdutoCategoriaListaItens Categoria
        {
            get;
            set;
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Descricao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Esta Em Falta (ESTAEMFALTA.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<bool> EstaEmFalta
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 15
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Preço (PRECO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> Preco
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela PRODUTO
    /// </summary>
    public partial interface IProdutoDao : IBusinessEntityDao<IProduto>
    {
    }
    
    /// <summary>
    /// DAO para a tabela PRODUTO
    /// </summary>
    public partial class ProdutoDao : BusinessEntityDao<Produto, IProduto>, IProdutoDao
    {
        
        public static ProdutoDao CreateInstance()
        {
            return CreateInstance<ProdutoDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo CATEGORIA.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
    public class ProdutoCategoriaListaItens : ListItems<ProdutoCategoriaListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Comida.
        /// </summary>
        public static ProdutoCategoriaListaItens ItemComida;
        
        /// <summary>
        /// Valor = 2, Item = Bebida.
        /// </summary>
        public static ProdutoCategoriaListaItens ItemBebida;
        
        /// <summary>
        /// Valor = 3, Item = Especial.
        /// </summary>
        public static ProdutoCategoriaListaItens ItemEspecial;
        
		public static implicit operator ProdutoCategoriaListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(ProdutoCategoriaListaItens item)
		{
			return item.Index;
		}
        
        static ProdutoCategoriaListaItens()
        {
			ItemComida = new ProdutoCategoriaListaItens {Index = 1, Description ="Comida"};
			ItemBebida = new ProdutoCategoriaListaItens {Index = 2, Description ="Bebida"};
			ItemEspecial = new ProdutoCategoriaListaItens {Index = 3, Description ="Especial"};

			Items.Add(ItemComida);
			Items.Add(ItemBebida);
			Items.Add(ItemEspecial);

        }
    }
    
    /// <summary>
    /// Produto
    /// </summary>
    [EntityDefinitionName("PRODUTO")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Produto : BusinessEntity<Produto>, IProduto
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Categoria = "CATEGORIA";
			public const string Descricao = "DESCRICAO";
			public const string EstaEmFalta = "ESTAEMFALTA";
			public const string Nome = "NOME";
			public const string Preco = "PRECO";
		}

        
        /// <summary>
        /// Categoria (CATEGORIA.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public ProdutoCategoriaListaItens Categoria
        {
            get
            {
                ListItem listItem = Fields["CATEGORIA"] as ListItem;
				if (listItem != null)
					return new ProdutoCategoriaListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["CATEGORIA"] = new ListItem(value.Index, value.Description);
				else
					Fields["CATEGORIA"] = null;
            }
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Descricao
        {
            get
            {
                return Fields["DESCRICAO"] as System.String;
            }
            set
            {
                Fields["DESCRICAO"] = value;
            }
        }
        
        /// <summary>
        /// Esta Em Falta (ESTAEMFALTA.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<bool> EstaEmFalta
        {
            get
            {
                return Fields["ESTAEMFALTA"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ESTAEMFALTA"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 15
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Preço (PRECO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> Preco
        {
            get
            {
                return Fields["PRECO"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["PRECO"] = value;
            }
        }
    }
}
